### ISSUE TITLE
STEP - MODULE 2 - NUMERACY 

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#101]
Your Turn: Observing Subitizing

Learner submits responses and can review answers but does not receive feedback.
Feedback has been written and is in the Subitizing --> Interactives folder.

**Comment by sarahlydic** [comment]
When I go to edit the questions, it looks like feedback has been entered. However, it isn't showing up for learners after submitting their answers. @mattsema can you fix?

**Comment by sarahlydic** [comment]
Tech will rebuild in lesson tool. Learner will watch video twice. Combine questions into 2 total questions.

**Comment by castl350** [comment]
new lesson version has been set up. needs to be tested again but initial issue addressed. closing ticket
