### ISSUE TITLE
STEP 2 Numeracy Counting and Cardinality Your Turn

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#109]
In the questions section I'd reinforce the word targeted and not just 'following' so revise to:
Describe what the teacher says and/or does related to the following targeted strategy:

Also most likely my view but I can't see my responses versus our responses.

Probably a question for Bridget/Jessica - as a coach use these responses to gauge teachers ability to observe and accurately note targeted strategies?

**Comment by sarahlydic** [comment]
Added the word targeted where appropriate. Emailed APJ about question for Bridget/Jessica.
