### ISSUE TITLE
STEP 2 Numeracy Counting and Cardinality TYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#110]
All of the correct answers were the first choice except for the true/false because the answer was false
#1 Capitalize the word 'one'
#4 at the start of the comment needs to be double quotation marks and not single
#8 capitalize the word 'so' 
#8 need to be sure that we're using the correct altogether

**Comment by sarahlydic** [comment]
Made all changes to typos. Leaving open for randomizing answers issue.
