### ISSUE TITLE
Mod 3 - Adding and Subtracting - Support Student Dev Trajectory

### ISSUE THREAD

**Issue by ryandkiley** [castl350/STEP#124]
Contractions?

Sentence one talks about subitizing

Number of objects - remove comma before so in last sentence

**Comment by ryandkiley** [comment]
Clicking continue to next lesson gives this error message - 
<img width="856" alt="error2" src="https://user-images.githubusercontent.com/30601742/29624574-6afc164c-87f7-11e7-96e1-639d075564a2.PNG">

**Comment by sarahlydic** [comment]
This whole activity is actually the subitizing activity that was copied as a placeholder. Not sure if we are adding the Developmental Trajectory for Adding and Subtracting? Tech issue (linking to next page) will be fixed once we know if this is being included.
