### ISSUE TITLE
Mod 3 - Plan Part 2

### ISSUE THREAD

**Issue by ryandkiley** [castl350/STEP#127]
Briefly describe.... subtracting TARGETED strategies

**Comment by sarahlydic** [comment]
@mattsema -- This is in Module 3, Adding and Subtracting. Can you make sure all PLAN (part 2) exercises include this edit to include the word "targeted"? (screenshot attached)
![screen shot 2017-08-24 at 11 31 43 am](https://user-images.githubusercontent.com/17276503/29674352-eb153354-88bf-11e7-8446-8e4f8fdc1983.png)

**Comment by sarahlydic** [comment]
"Counting on" AND "Counting back from" are 2 separate strategies. Separate

**Comment by mattsema** [comment]
separated on/back from strategies and corrected text
