### ISSUE TITLE
Sharing Fairly - Complete Planning

### ISSUE THREAD

**Issue by ryandkiley** [castl350/STEP#134]
Briefly describe... fairly TARGETED strategies

**Comment by sarahlydic** [comment]
@mattsema Can you fix?
![screen shot 2017-08-24 at 12 07 44 pm](https://user-images.githubusercontent.com/17276503/29676029-e4c44ddc-88c4-11e7-96b1-63155be12cea.png)

**Comment by mattsema** [comment]
text added
