### ISSUE TITLE
Mod 4 - Your Turn: Recognizing Misconceptions

### ISSUE THREAD

**Issue by ryandkiley** [castl350/STEP#137]
Second sentence - comma after "In this lesson,"

**Comment by ryandkiley** [comment]
For question 1, the options should be in quotes to show the teacher is speaking.

**Comment by ryandkiley** [comment]
For question 3, one of the choices has an a) in front of the response.

Also, in the "correct" feedback, the second sentence should say "... facing down, studentS will often ... "

**Comment by sarahlydic** [comment]
Typos corrected
