### ISSUE TITLE
Mod 4 - Shape Prop Plan (Part 2)

### ISSUE THREAD

**Issue by ryandkiley** [castl350/STEP#138]
Clicking "continue to planning exercise" in Part 1 takes to Part 2 planning for directionality, order, and position

**Comment by ryandkiley** [comment]
Briefly describe how you plan.... properties TARGETED strategies

**Comment by sarahlydic** [comment]
@mattsema Can you fix?

**Comment by mattsema** [comment]
link and text corrected
