### ISSUE TITLE
Mod 4 - Directionality Your Turn

### ISSUE THREAD

**Issue by ryandkiley** [castl350/STEP#142]
Question 2 - should have a comma after "After the science experiment, "

Question 2 - feedback does not match example. Feedback talks about books, but the scenario is about balls floating in a cup.

**Comment by ryandkiley** [comment]
If you get the answer wrong and click the button that says "Incorrect. Please try again" It takes you to the next question.

**Comment by ryandkiley** [comment]
The question about sinking and floating isn't very clear. It might be helpful to talk more about the order of the process, like have the teacher reflect on what they did, "First, we put a ball in this cup and it floated. Next we put a ball...." I got this one wrong because I thought it was talking about the direction of the ball going up or down :(

**Comment by ryandkiley** [comment]
Question 4 - children waiting in line for slide.

Teachers comment should have comma "I know it's hard to wait, but..."

**Comment by sarahlydic** [comment]
Typos & question redirection fixed. Leaving open for content.
