### ISSUE TITLE
Step 2 Numeracy 3 Comparing and Ordering TYK 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#151]
Qu #1 and #2 inconsistent use of periods at the end - some have periods and some don't 
Qu #3 in the question chance concepts to concept. In the scenario there should be a comma after the word carpet not a new sentence. Revise to: carpet, one pile  
Qu #6 and #7 add the word targeted before strategy revise to:
 #6 One effective targeted strategy
#7 which targeted strategy
Are qu #6 and #7 related? If so then revise so that is reflected by consistent use of teacher name and by saying something like in the example above
Also are qus #6 and #7 too similar because they are asking the same thing?
#10 consistent use of tense so revise to match: realizes
Should it be quite large instead of quite big?

**Comment by sarahlydic** [comment]
Fixed typos. Left word "big" instead of "large." Leaving open for content on Qu 6 & 7.

**Comment by castl350** [comment]
Sarah, related to Question 7. It is not related to question 6. Matt forgot to enter the scenario that belongs with that question. I'm including it here..it also needs an image included, which i'll draw now.

7. In this example, Ms. Jackie is using which strategy to support students’ ability to compare and order ?

Ms. Jackie has the numbers 1 through 5 in front her (include image with question). She gives five students a bag with a group of objects inside that matches one of the numbers and ask students to pull them out. The students see 2 carrots, 1 marble, 4 pencils, 3 bouncy balls, and 5 building blocks. Ms. Jackie points to the numbers and asks, ”Let’s order our group of objects from smallest to largest. Which group has only one object, our smallest number? When one student, Jaylan, points to the marble, Ms. Jackie says, “Nice job.  Now, which group of objects will come next? What’s the next number on our chart?” When Kayla says, “Two!”, Ms. Jackie follows up by saying, “That’s right. Two is our next number. Which group  has two objects?”

a)	Prompting students to count and then verify that counting led to correct judgement
b)	Encouraging students to use matching to compare groups of objects
c)	Helping students use their understanding of the counting sequence

**Comment by castl350** [comment]
Sarah and matt, once the scenario is in for question 7, and the images is in as well...please close this ticket?

**Comment by mattsema** [comment]
scenario and image added to question 7

**Comment by sarahlydic** [comment]
Just wanted to document text edits I made. Screenshot attached - SVL
![screen shot 2017-08-29 at 4 43 17 pm](https://user-images.githubusercontent.com/17276503/29844917-ec989112-8cde-11e7-8159-d69fa3c44ae2.png)
