### ISSUE TITLE
Step 2 Numeracy 3 Comparing and Ordering TYK error message

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#152]
When I clicked next I got this message:
![screen shot 2017-08-25 at 7 23 22 am](https://user-images.githubusercontent.com/19825720/29712135-58aae52a-8966-11e7-8fc0-793e0511c63a.png)

But the next time I did it that error message didn't come up?

**Comment by sarahlydic** [comment]
This has happened to me when I've had 2 browser windows open to castllearning, which logged me out... @mattsema Do you think that's what happened here?
