### ISSUE TITLE
Step 2 Numeracy 4 Recognizing and Writing Numerals 1. What is it CYK 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#158]
Not sure you can fix this but thought that I'd point out:

![screen shot 2017-08-25 at 8 01 15 am](https://user-images.githubusercontent.com/19825720/29713345-25f4a73c-896c-11e7-9e88-3834473f32f7.png)

**Comment by sarahlydic** [comment]
known issue. cannot fix.
