### ISSUE TITLE
Step 2 Numeracy 4 Recognizing and Writing Numerals 4. Your Turn  Scenarios

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#165]
Scenario 1 
Typo - should be how and not who
Feedback - not sure which words should be number and which should be numeral or if it matters?

Scenario 2
Not sure about this or if it even matters (google check wasn't super helpful) should be colored OR hats of different colors and then with a certain colored hat 

Scenario 3
Typo - should be students not student
Feedback - need a comma after the word asks in second to last sentence

Scenario 4
Feedback - missing comma after She says

Scenario 5
Typo - take out the word 'an' - just read she used to create artwork
Feedback - should be 'an' and not and before S and the comma should be inside the quotation marks; take out the word 'around' and just have first time,

**Comment by sarahlydic** [comment]
Fixed
