### ISSUE TITLE
STEP 2 Numeracy 4 Recognizing and Writing Numerals TYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#166]
#2 comma should be inside the quotation marks, "8." Also need to be consistent if this is Ms. Patel or Mr. Patel; revise to ... and says, "Can you find the number 8?" (but maybe he should say numeral?)

#3 need a comma after the word says in three places:
Karen counts the number of brown dinosaurs and says
As Karen writes the numeral, she says
As she writes the numeral, she says
Also capitalize the 's' in the first small curve and the 's' in the first small line

#6 put targeted in front of the word strategy
Capitalize the word which
Revise sentence to read Mr. McCauley holds the six card and the two card 
Capitalize the word mine
Take out option d

#7 put targeted in front of the word strategy
put the period inside the quotation marks
Put double quotes at the end of "Maybe this one?" and "... figure it out."
Take out option d

#8 capitalize the word what, "What number ...
Capitalize the word three responds, "Three," 
Capitalize the word how "How else ..."
after the words stickers put double quotation marks

There are only 8 questions for this TYK which I believe we said was ok as long as we felt that all material was covered.

These is also feedback for this TYK which I don't think that we're providing ... 

#3 Not sure what the correct answer is?

**Comment by sarahlydic** [comment]
Corrected all. However, for #6 and #7, I don't know what option you saw as option d (to take out) because answers are randomized. @ajp9e can you clarify?

I also don't know what the correct answer is for #3 or if we're providing feedback. @ajp9e can you find out this info.?

**Comment by sarahlydic** [comment]
@mattsema will address d being blank. SVL will make sure all feedback in in questions.

**Comment by sarahlydic** [comment]
Number 3 on TYK - correct answer is f. -- but this is getting marked as incorrect. (Moodle will correct last sentence automatically.)

**Comment by mattsema** [comment]
all issues addressed
