### ISSUE TITLE
M1 Numeracy - Lessons

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#173]
3 lessons are under review. When approved, can be added.
Files are on tech server as:
M1_S0_A0_NumeracyIntro_8292017_revision
M2_S3_A2_ComparingOrdering_HowDevelop_82912017_FINAL
M1_S4_A2_RecognizeWrite_HowDevelop_8292017_FINAL

**Comment by mattsema** [comment]
numeracy intro and c & o how have been replaced
waiting on final edits for rec & write how

**Comment by mattsema** [comment]
remaining video noted in #225 closing this issue
