### ISSUE TITLE
M0 and M1 Documents

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#174]
The following documents need to be linked --

**M0:**
STEP_INTRO_8_2_FINAL (link within the HTML page for Introduction and Objectives. add to top section under "Meet the Faces" as well?)
STEP_FOUNDATIONAL_8_29_FINAL (link within the HTML page Foundational and Targeted Strategies - replace current doc)

**M1:**
STEP_NUMERACY_8_29_FINAL (link in Numeracy overview - replace current doc)
STEP_COMPARING_8_29_FINAL (link in Comparing section - replace current doc)
STEP_COUNTING_8_29_FINAL (link in Counting section - replace current doc)
STEP_RECOGNIZING_8_29_FINAL (link in Recognizing section - replace current doc)
STEP_SUBITIZING_8_29_FINAL (link in Subitizing section - replace current doc)

These are saved in
STEP --> content --> companion docs --> Pilot2_STEPdocs

**NOTE:** The Targeted Strategies document may not be ready for Thursday. Create link and add document after finalized.

**Comment by mattsema** [comment]
Closing this issue adding targeted strategy doc as new issue.  All other documents linked
