### ISSUE TITLE
Module 1 Intro and Objectives pdf

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#177]
Is the pdf supposed to look like this or is the word goals supposed to be blue? Just wondering
![screen shot 2017-08-30 at 10 09 58 am](https://user-images.githubusercontent.com/19825720/29876677-78e46d1c-8d6b-11e7-8fec-e433477a567a.png)

**Comment by castl350** [comment]
The PDF is not supposed to be there. It should be a separate link on the list of the LMS..i will fix this.

**Comment by castl350** [comment]
put on the LMS
