### ISSUE TITLE
Module 1 Introduction and Objectives

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#178]
Aren't they already doing a module so is this confusing? Revise to 'Be ready for the other STEP math modules' or something like that?
![screen shot 2017-08-30 at 10 12 11 am](https://user-images.githubusercontent.com/19825720/29876844-d38aa0e2-8d6b-11e7-89b9-1387ecede634.png)

**Comment by castl350** [comment]
just took it out...it was a bit confusing and not necessary.
