### ISSUE TITLE
Module 1 6. Your Journey Through This Learning Experience CYK - question and typo

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#184]
For the items that are true - are we including the sentence 'This statement is true.' Makes sense to have when it's not true/false ... just wondering ...

change you're to you'll or you will

**Comment by mattsema** [comment]
corrected text, and adding screenshot for refrence on statement
![screen shot 2017-08-30 at 11 56 49 am](https://user-images.githubusercontent.com/2487659/29882230-62833256-8d7a-11e7-8d58-504780cd2c6f.png)

**Comment by castl350** [comment]
I think either would work...we have never added "This statement is true" because Your answer is right above in green? Either is fine but please do not worry about changing more of these....
