### ISSUE TITLE
Module 1 8. Reflecting on Your Goals Qu'aire #8

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#186]
Take out quotation marks in question
change question mark at end to period - Check all that apply.

In the list I understand why The Objective and Descriptive Lens for Viewing Classrooms is reworded from home page that lists 'Becoming a Better Observer' but I'm not sure where info re: How to Integrate Math Learning throughout the Day occurred? Was this in the intro or just general theme?

**Comment by castl350** [comment]
Waiting on comment from matt about ability to take out the last item integrating option.

**Comment by castl350** [comment]
done
