### ISSUE TITLE
Module 1 TYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#187]
#2 I'd change question wording to, "When it comes to supporting children's learning, teachers' interactions ..."
Also are we using children? Should this be changed to students' learning?

#5 Should be Let's (with an apostrophe) and take our comma so it reads "... top right of the picture or the bottom right?" with no comma

**Comment by mattsema** [comment]
adjusted question 5

**Comment by castl350** [comment]
changed the wording of 2 but left the term child as it is in context to development.
