### ISSUE TITLE
Module 1 TYK missing feedback

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#188]
I am pretty sure that this is a known issue and that Anna is working on this but I wanted to note it just in case.

**Comment by castl350** [comment]
It is not a known case :)..thank you for catching it.

**Comment by castl350** [comment]
Ticket in progress.  Created feedback and sent to Jessica and Anna for review.

**Comment by castl350** [comment]
This is in now, but i feel like it may be inconsistent with the other TYKs in terms of feedback..should it have the MC letter in the feedback,e example...keep open until it's checked.
