### ISSUE TITLE
Module 1 Follow Up Questions

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#189]
Overall use of the word session - should this be module? as this module only has the one session? We use it a ton so maybe not change?

#1 3rd item Instead of the word 'course' change to 'learning experience' (3rd item down)

#5 do teachers know the training as a training or as a kick-off meeting. Kick-off is maybe our in house term? and then within the question we saw 'course workshop' so I think we should be consistent and go with training - in each of the items needs to be changed to training versus workshop

Also last question change to 'learning experience' and not course in a and d

In general I think that I caught all the places where we say course but may give it a once over when you're in there editing/revising.

**Comment by mattsema** [comment]
corrected instances of course with learning experience or website (as in case of last question)
the intro module is really a one session module, the word can still work

**Comment by castl350** [comment]
I agree on the use of the word session. It is a module that happens to have 1 session. we will have similar situations come up in the patterning and measurement modules, which only have 1 skill/1 session.
