### ISSUE TITLE
Module 1 Practice: Tape Your Classroom 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#190]
In the first sentence take out 'session' and have it just read ... you'll be taping your classroom interactions as a way to practice using the iPad.
Take out comma after technology works 

Also we use tablet/iPad interchangeably and I think that if we tell teachers tomorrow that it's called both we can use both ... but if we think that they won't get that then under Basic Taping Steps change table to iPad

**Comment by castl350** [comment]
done
