### ISSUE TITLE
Module 2: Numeracy S4 Your Turn

### ISSUE THREAD

**Issue by mattsema** [castl350/STEP#191]
Answer option is being turned into link by moodle because the text exactly matches the lesson name, Strategy 1: Discuss Numeral Appearance.  Strategy 2 does not get linked because we use "Use" for the activity name and "Provide" in the your turn question.  If user selects the option for strategy 1, they are linked to the activity and taken out of the your turn.
![screen shot 2017-08-30 at 11 17 49 am](https://user-images.githubusercontent.com/2487659/29880316-762dcd34-8d75-11e7-9689-e6fa5c57f925.png)

**Comment by castl350** [comment]
weird..will address this across the board...changed all to Providing...and Discussing...so they don't match up with the exact title and become links..
