### ISSUE TITLE
Module 2 Meet the Faces

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#193]
I see that we have added who is guiding through each session ... but it hasn't been updated/added for Sonia

In these sentences about who is guiding should the sessions be capitalized?
... through the Counting and Cardinality session
... through the Subitizing session
etc

**Comment by castl350** [comment]
nope..not capitalized....

**Comment by castl350** [comment]
switched it so it says they will guide us through the session focused on the skill of Counting....that way it can feel more formal here.

added sonia's session.
