### ISSUE TITLE
Module 2 Subitizing 4. Your Turn 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#197]
Spotting the Targeted Steps
3rd step add a comma after 'the number word'

Feedback for first time play video - compare your answer to ours
- Quickly shows (add s)
- Ask (add s) and in the paragraph below this
add a comma after ... the first dot card
capitalize Tell and put the period inside the quotation marks

- Help (add s) 
add a comma after 'the number word'

Last sentence should read ... when you see important targeted steps taking place.

Spotting the Foundational Strategies
add 's' to support (This teacher supports ...)
change children's to students'
Capitalize the 's' in So
put a period instead of comma after - ... just know how many there are." then capitalize the - The teacher is explaining ... 

In next paragraph change to
This comment is a great start towards helping students see ... 
... by saying something like, "Sometimes when we ... 
Add quotation marks after ... in this small group."
Add the word 'to' - ... help students connect subitizing to the real world.

**Comment by castl350** [comment]
done.
