### ISSUE TITLE
Module 2 Subitizing  5. Intergrating ... 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#199]
Routines
- change stick to sticker

Transitions
- add a comma after ... with a quantity filled in, 

Meals 
- add a comma after rectangular shape
- add a comma after rectangular arrangement

Outdoor Time 
- add a comma after rectangular shape
- add comma after rectangular arrangement

**Comment by castl350** [comment]
This is hidden from learners? We are not doing this activity?

**Comment by castl350** [comment]
I checked and you would not see this from a student view. We decided to get rid of these in the sessions because it adds to the workload it's text that is available in the companion docs.
