### ISSUE TITLE
Module 2 Subitizing PLAN (part 1)

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#203]
To be specific and consistent do we want to change opening paragraph to ... implement targeted steps and foundational strategies ...
- In the session line up we talk about steps/strategies first and then foundational strategies 

2. Complete the Planning Exercise - same suggestion as above
... make a plan for implementing targeted steps and foundational strategies ...

**Comment by mattsema** [comment]
corrected using emailed changes
