### ISSUE TITLE
Module 2 Counting and Cardinality 2. How Does it Develop CYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#207]
The CYK is about 3 year olds, when I brought this up to Anna she responded with:
_I think there are a couple reasons why this CYK relates to what a 3 year old can do. One reason is that it gets pretty complicated around ages 4 and 5, so it was hard to expect learners to have "take-aways" for those ages. Also, three year olds were part of the pilot.

However, this video lesson has been re-done since this CYK was written, so I think it's probably easier for learners to have some key take-aways from the lesson for 4 and 5 year olds. Maybe a replacement CYK could have something to do with 4 year olds and cardinality?_

Kathy your thoughts on this? I hate to even ask because CYK questions are my nemesis but I thought that I should circle back around. Thanks

**Comment by castl350** [comment]
leave it as is....
