### ISSUE TITLE
Counting and Cardinality 4. Your Turn Compare your answer to ours

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#211]
Say counting words in correspondence with objects:
- capitalize the word watch and add comma - "Watch me count,"

Teach "keeping track" strategies 
- 3rd bullet capitalize She's 

Count to answer "how many":
1st bullet capitalize The "The last number ..."
2nd bullet capitalize how - .. the teachers asks, "How many fish," 
capitalize ... responds, "Two,"
capitalize good ... by saying, "Good ..."

**Comment by castl350** [comment]
done...adjusted bullet 3 slightly differently.
