### ISSUE TITLE
Counting and Cardinality TYK feedback

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#214]
Take out the right answer at the beginning of the feedback. It is redundant to me. It's noted 3 times what the right answer don't need it a 4th time in my opinion.

#8 change to all together

**Comment by mattsema** [comment]
change was made to question 8

I double checked the feedback for the other three sessions.  It is mostly consistent with including the correct answer.  If we go with this change, it would need to be done to all tyks

**Comment by ajp9e** [comment]
I think that we leave it in there then ...

**Comment by castl350** [comment]
i'm gonna close it then
