### ISSUE TITLE
Counting and Cardinality PLAN (part 1) and part 2

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#216]
ordering of strategies - consider changing to targeted and foundational as that is how they occur in the session 

For this part of the STEP process, you will complete a planning exercise, showing how you plan to implement targeted and foundational strategies to support children’s counting and cardinality skills.

And the same for the bottom paragraph and for the landing page of answering the questions.

**Comment by mattsema** [comment]
switched order of targeted and foundational part 1 and part 2
