### ISSUE TITLE
Comparing and Ordering Numbers 1. What is ... CYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#217]
#1 CYK
Arrange a group of numbers from largest to smallest, or smallest to largest. - Take out comma

See a group of objects quickly, and know how many there are. - Take out comma

Determine whether one number, or objects in a group, is more than, less than, or the same amount as another number, or number of objects in another group - add a period and take out the last comma 
In feedback take out same last comma as noted above

#2 CYK
See a group of objects quickly, and know how many there are. Take out comma

Determine whether one number, or objects in a group, is more than, less than, or the same amount as another number, or number of objects in another group - add period and take out last comma 

Arrange a group of numbers from largest to smallest, or smallest to largest - add period and take out comma 
In correct feedback take out same comma

**Comment by mattsema** [comment]
adjusted text as noted
