### ISSUE TITLE
Comparing and Ordering Numbers Strategy 3 CYKs 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#219]
#1 Take out 
- Check Your Knowledge
- **The following question is designed to review the three strategies you learned about in this session. (we don't have this for the other ones)
- True or False: 

Feedback - take out 'This statement is true.'

#2 Take out
- Check Your Knowledge
**The following question is designed to review the three strategies you learned about in this session.

**Comment by castl350** [comment]
will add it to CC
