### ISSUE TITLE
Comparing and Ordering Numbers 4. Your Turn

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#220]
1st Compare your answer to ours:
- 1st bullet at the end of the sentence period can go inside the quotation marks
- 3rd bullet capitalize the word equal and put comma inside the quotation marks ... replies, "Equal," the teacher ... 

2st Compare your answer to ours:
- reword 2nd bullet
When the teacher sees that Malakai may not understand the term "less", she uses the terms "smaller" instead. She also scaffolds by using her fingers ... 
- 4th bullet add apostrophe to students (students' understanding) and I'd write the word zero for the first one instead of 0 but leave 0 for the second place

**Comment by mattsema** [comment]
changes made
