### ISSUE TITLE
Comparing and Ordering Numbers TYK feedback

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#222]
#3 capitalize the 'b' in both
 - Both A and B. In this ...

#4 change the to this - In this scenario (matches feedback above)
need space between with 5 

#5 take out - That's right and change to "A. As young children's ..."

#8 Take out - That's right.

#9 put a comma after amounts - "... When students have to compare two amounts, as described in this scenario, they ..."

**Comment by castl350** [comment]
got em all...
