### ISSUE TITLE
Recognizing and Writing Numerals 2. How Does it Develop - missing video

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#225]
Known issue?

**Comment by mattsema** [comment]
Kathy, are we waiting on any more final edits on this video?  The last I saw, you had some notes before it would be complete.

**Comment by castl350** [comment]
Yep..this one has one issue that needs to be addressed by Sarah before we can post it..but i was waiting on confirmation from Jessica about that....it's super close...
