### ISSUE TITLE
Recognizing and Writing 2. How to Support CYKs

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#227]
#1 Take out:
Check Your Knowledge
**The following question is designed to review the three strategies you learned about in this session.

#2 Take out:
Check Your Knowledge
**The following question is designed to review the three strategies you learned about in this session.
True or False:

**Comment by castl350** [comment]
I put that in purposefully so that people would not think the question would be specific to the lesson they just watched..if it's not in the others, we should add it there...
