### ISSUE TITLE
Recognizing and Writing Numerals Your Turn 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#228]
Video #2 feedback
She focuses students’ attention to the parts of 5,1, and 2 as she writes them, which helps student construct a mental image of each numeral.
Second 'student' needs an 's' - students 

Make his hat, makes his back, make his tummy round and fat.” - should all be make singular

Video #4 feedback
Over time, this will help the student recognize the numerals on the cards and connect them with the quantity they represents. - take 's' off of represents

Video #5 first page
the teacher asks the student the write the numeral 8 next to her work. - add the word 'to'
Revise "... the teacher asks the student to write the ..."

Feedback for both wrong answers is too much
![screen shot 2017-08-30 at 9 47 12 pm](https://user-images.githubusercontent.com/19825720/29902553-d1553b78-8dcc-11e7-9d26-cb9e7ee935e8.png)

**Comment by mattsema** [comment]
made corrections for questions 2 & 4 and revised question page of question 5
still need to address feedback for question 5

**Comment by castl350** [comment]
i limited feedback for all wrong answers....
