### ISSUE TITLE
Recognizing and Writing Numerals TYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#229]
#3  Item Connecting a numerals with the quantity it represents - take 's' off numeral 

#6 Mr. McCauley holds the six card and the two card next to each other and says, “Very good. How could you tell these two numerals look different?”  - should be nine card not two card

#7 Ms. Creamer - this name makes smile but maybe change to Ms. Kramer? Never mind ... there are lots of Ms. Creamers!

**Comment by mattsema** [comment]
changes addressed
