### ISSUE TITLE
What is Adding and Subtracting CYK#2 Feedback

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#237]
Inconsistent use of quotation marks for problem types:
That's right. This statement is false. Typically, "result unknown" problem types, such as 2 + 3 = ?,  are the easiest for young children to figure out. Change unknown problem types, such as 2 + ? = 4, or "start unknown problem types, such as ? + 1 = 5, are more difficult.

Change to:
That's right. This statement is false. Typically, "result unknown" problem types, such as 2 + 3 = ?,  are the easiest for young children to figure out. "Change unknown" problem types, such as 2 + ? = 4, or "start unknown" problem types, such as ? + 1 = 5, are more difficult.

**Comment by castl350** [comment]
corrected
