### ISSUE TITLE
2. How Does it Develop - Adding and Substracting CYK #1

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#240]
We have
True or False: Most four-year-olds rely heavily on concrete representations, such as objects, fingers, or marks, when they are working on addition or subtraction problems.

In the CYK T/F question for What is It we don't have the True or False at the beginning. Not sure what the rule is but I think that we don't have True or False at the beginning of the question.

And for the feedback at the end change to  ... such as objects, fingers, or marks. Missing the 'or'

**Comment by castl350** [comment]
True or False also does not appear in Numeracy.  Removed and corrected feedback
