### ISSUE TITLE
2. How Does it Develop Adding and Subtracting CYK #2

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#241]
Not sure that this is how we do these kinds of questions?
All of the following are ways that children's abilities to solve addition and subtractions problems grow -- except: 

I think we do something like this:
All of the following are ways that children's abilities to solve addition and subtractions problems grow EXCEPT:  and put it in caps

For example in Strategies CYK we have:
All of the following statements related to the "counting all" strategy are true, EXCEPT: 

And I am not sure about whether or not we have periods at the end of the listed items - in looking at the All About CYK list of items - we don't but I wasn't sure but then for Strategies CYK #1  we do have periods ... 

In the feedback take the 's' off of subtraction
Not sure if the 't' in The should be capitalized after 1) if it is then should the others be capitalized?

**Comment by castl350** [comment]
the list items are not complete sentences where some like strategies cyk 1 are.  All other points corrected
