### ISSUE TITLE
Strategies CYK #2

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#243]
All of the following statements related to the "counting on" and "counting back" From strategies are true, EXCEPT:

From shouldn't be capitalized 

On the home page for 3. How Can You Support it? short-cuts is hyphenated and not in quotations but it's not the same here:
These strategies are a bit more advanced and offer students “short cuts” to add or subtract.

In the feedback we have:
That's right. This statement is false. While the "counting all" strategy does encourage students to start their count at 1 to solve addition or subtraction problems, the "counting on" and "counting back from" strategies don't. 

So for the "counting back from" I think that we just need to be consistent

**Comment by castl350** [comment]
corrected
