### ISSUE TITLE
Adding and Subtracting 4. Your Turn

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#244]
In this exercise, your goal is to: ---- missing comma? Not sure how we are doing.

This is inconsistent for Numeracy
Subitizing: In this exercise, our goal is to:
Counting and Cardinality: In this exercise, our goal is to:
Comparing and Ordering Numbers: In this exercise your goal is to:
Recognizing and Writing Numerals:In this exercise, your goal is to:

**Comment by castl350** [comment]
made consistent
