### ISSUE TITLE
4. Your Turn Identifying the Targeted Strategy Scenario 1, Part 1

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#245]
Scenario 1, Part 1
Consider changing to dog bones instead of doggy bones to be consistent

When you choose the wrong answer it just refreshes the page without any information about wh/not your selection is right or wrong - is this how this is supposed to work?

Scenario 1, Part 2
saying, “one, two, three, four.” - Capitalize one
Feedback - 2) counts the objects the other group ---- add the word 'in' - 2) counts the objects in the other group
Consider putting quotation marks around Counting all in the second sentence to be consistent

**Comment by castl350** [comment]
addressed all
