### ISSUE TITLE
4. Your Turn Identifying the Targeted Strategy Scenario 2, Part 1

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#246]
Feedback for Part 1
That’s right. This is a “change unknown” addition problem type because the original amount is known (2), and the result is known (4), but the change--in this case, the amount to add--is unknown. “Change unknown” addition problems are typically more challenging for young students because they require students to determine how many objects are involved in the action of the problem. In this scenario, the action of the problem involves adding more buttons to the original group of buttons.

Rather than -- after change, consider using a comma, "... the change, in this case the amount to add, is unknown.

Part 2 - Identifying the Strategy
Miguel starts by saying, “two...”    capitalize the word two
And I would consider changing to read the following as I think that it will match the image:,
"Miguel starts by holding up two fingers and saying, "Two," and then he says "three" while putting up another finger and then says "four" while putting up another finger. He looks at his fingers says, "Two! We need two more buttons."

**Comment by castl350** [comment]
corrected
