### ISSUE TITLE
6. Adding and Executive Function

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#247]
Now that you've had a chance to learn how we can support children's subitizing skills, let's shift to the third big idea: That children's executive function and mathematics skills work hand-in-hand.

Should be adding skills and not subitizing

In this lesson, we'll rewatch a subitizing lesson that you've already seen. This time, we'll pay special attention to how executive function plays a role in children's abilities to subitize.

Again in both places needs to change to (I think):
In this lesson, we'll rewatch an adding lesson that you've already seen. This time, we'll pay special attention to how executive function plays a role in children's abilities to add.

**Comment by castl350** [comment]
updated language
