### ISSUE TITLE
TYK 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#248]
The first choice is the right answer for questions: 2, 3, 4, 6, 7, 8 - consider mixing it up a little?

#2 For teacher's name be consistent - either do Roberson or Robertson
#4 is italicized is that be cause it's a story? The others aren't italicized is that because they're scenarios? It seems that way :)
#5 Take out the period after "Three!" and the comma after "How did you know?"
#8 Do we typically have True or False at the beginning of questions?

In the feedback sometimes we use number words in the parenthesis and sometimes we use numerals) not sure it matters ... just an observation

**Comment by castl350** [comment]
fixed answer choices, and inconsistencies
