### ISSUE TITLE
Sharing Fairly Intro and Objectives

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#250]
Currently reads:
In this session, you'll learn all about the second Numeracy skill, Sharing Fairly.

Change to:
In this session, you'll learn all about the second skill in the area of Operations: Sharing Fairly

This is what we have in Adding and Subtracting:
After this session, you'll apply what you have learned about this skill as you:

    Plan and practice implementing an activity in your classroom.
    Observe your own implementation and reflect on your practice.

Not sure if we want these to match exactly? This is what we have for Sharing Fairly:
After this session, you'll apply what you have learned as you:

    Plan and practice implementing an activity in your own classroom.
    Observe your own implementation and reflect on your practice.

They're both very similar but not the same ... not sure how much it matters?

**Comment by castl350** [comment]
adjusted text
