### ISSUE TITLE
Sharing Fairly Your Turn Compare Your Answer

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#258]
Capitalize the word 'just' ... between when she says, "Just you three ...

Capitalize the word 'they' in the second step and consider revising to:
... the teacher scaffolds his thinking by saying, “They each have one. You got to share with yourself and you get? (pause) She has one; Chloe has one. How many should you start with to make it fair?” 

In the third step 3 line down capitalize the word 'did' and add question mark - “Did you share fairly with your friends? Do you all have the same amount of cookies? Is that fair?”

**Comment by castl350** [comment]
corrected text
