### ISSUE TITLE
Sharing Fairly TYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#259]
There are only 7 questions - I think that they reflect the content well so it's ok but maybe we want more to match up with other sessions? 

Q#1, 3 is missing feedback embedded in the question like the others - at first I thought it was because I chose the right answers but for #4 I also chose the right answer and there was feedback embedded 

Q#2 feedback add 's' to odd numbers near end of third line

Q#7 Change 'That's correct.' to 'That's right.' to be consistent with others and put a comma after (four)

**Comment by castl350** [comment]
Allison, will you please confirm the correction for adding 's' to odd numbers?

**Comment by ajp9e** [comment]
Matt/Sarah/Kathy - sorry but I can't see any feedback for TYKQ#2 as to wh/not should add 's'
![screen shot 2018-01-08 at 3 12 23 pm](https://user-images.githubusercontent.com/19825720/34690269-753568e2-f486-11e7-9488-f09b47485098.png)

**Comment by ajp9e** [comment]
Sorry couldn't figure out how to go back to comment on what I just wrote.

Taking this TYK again I am not always getting detailed feedback, as in the screenshot that I just sent so I am a little confused. Thanks for your help with this. I am at home and able to talk on phone 434-296-5098 if it would be easier to talk through.

**Comment by castl350** [comment]
thanks allison, I ended up finding it
