### ISSUE TITLE
Describing and Comparing - Your Turn Feedback Video Scenario #1

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#304]
VIDEO SCENARIO 1: In this scenario, we’ll see a teacher introduce a lesson where children will be comparing the weight of this different objects.

- change 'this' to 'these' 

Feedback
Compare your answer to ours:

First bullet - capitalize the 'T' in today

Second bullet - capitalize the 'I' in if

Third bullet - She clarifies for one student that “heavy isn’t that it’s too big”. change to (add comma and capitalize the h in heavy):
She clarifies for one student that, “Heavy isn’t that it’s too big”.

Fourth bullet - when she says, “it’s too heavy.” - capitalize the 'I' in it's

Fifth bullet - ... that “heavy is something ...
Take out the word that and put a comma after the word summarize and capitalize the 'H' in heavy

**Comment by mattsema** [comment]
changes made
