### ISSUE TITLE
Describing and Comparing - TYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#306]
**Test Questions**
Q#8 ... and which is the shortest. 
Add end quotation marks after the word shortest

**Test Feedback**
Q#4 At first, young children tend to focus on the attributes and length and volume first.
- should read of and not and
At first, young children tend to focus on the attributes of length and volume first.

Q#7
 - The teacher is drawing attention several of the stick’s  ...
Add the word 'to' in between the words drawing and attention
The teacher is drawing attention to several of the stick’s  ...

- ... the attributes two different objects ...
Add the word of in between the words attributes and two 
... the attributes of two different objects ...

Q#8
- ... and along the way
add a comma after the word and

- which make sense.
add an 's' to the word make
which makes sense.

**Comment by mattsema** [comment]
changes made
