### ISSUE TITLE
Decribing and Comparing AND Measuring lesson plans 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#309]
The lesson plans are the same for both of these sessions - is it supposed to be that way?

I would check this with Ryan b/c the lessons listed in part 2 are these:

What lesson from the STEP learning website will you be implementing? *

    Comparing Weight I
    Comparing Weight II
    Ordering by Height
    Ordering by Weight 

Which seem to me to be the ones that should be in part 1 - but I would check with Ryan

**Comment by mattsema** [comment]
used the handouts to change and confirm lessons as necessary
