### ISSUE TITLE
Describing and Comparing plan part 2

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#310]
Here are the lesson that are listed for Describing and Comparing - these are not the lessons that were listed in part 1 - what lessons should be here?

What lesson from the STEP learning website will you be implementing? *

    Comparing Weight I
    Comparing Weight II
    Ordering by Height
    Ordering by Weight

**Comment by mattsema** [comment]
The lessons listed are correct.  Part 1 now has those four lessons listed and linked.
