### ISSUE TITLE
0104 Numeracy: Rec and Writing Numerals -  Your Turn: Observing and Spotting the Strategies

### ISSUE THREAD

**Issue by kneesen22** [castl350/STEP#313]
all Incorrect feedback is still set to Moodle style where the learner has a chance to try again until they are correct.

<img width="658" alt="Screen Shot 2019-05-13 at 7 53 59 AM" src="https://user-images.githubusercontent.com/2520615/57620815-e1a80400-7557-11e9-94b7-b119b828b29d.png">

**Comment by ryandkiley** [comment]
Fixed!
