### ISSUE TITLE
03-01 Your turn - Geometry Misconceptions

### ISSUE THREAD

**Issue by kneesen22** [castl350/STEP#320]
Matt, will you take a look at this one...this feedback currently has images in it...but it's not displaying at all...is the images in the feedback causing it not to show? If so, i will set activity differently.

https://curryvirginia.instructure.com/courses/1418/quizzes/3003/edit

**Comment by kneesen22** [comment]
Matt, think i might have figured it out...during my first test..i didn't select any answers.....so it didn't show question specific feedback....once i chose answers..it worked..

**Comment by mattsema** [comment]
Confirmed that the images show with feedback when a user selects an answer.  Also noting that general comments can be used to show feedback regardless of answer.
