### ISSUE TITLE
"and" missing

### ISSUE THREAD

**Issue by monicasyl10** [castl350/STEP#334]
"teachers receive individualized feedback on the instruction, identify areas of success and room for growth" should be "teachers receive individualized feedback on the instruction and identify areas of success and room for growth."

[http://dev.steplearning.org/about/mission.php](url)

![image](https://user-images.githubusercontent.com/54451784/63711462-797ce580-c809-11e9-84c3-ad3e8b5b850e.png)

**Comment by mattsema** [comment]
fixed
