### ISSUE TITLE
space missing

### ISSUE THREAD

**Issue by monicasyl10** [castl350/STEP#335]
space missing between the words "variety" and "of": "Executive function (EF) skills are the cognitive processes that helps us function in daily life and master a varietyof different tasks."

[http://dev.steplearning.org/about/math_ef.php](url)

![image](https://user-images.githubusercontent.com/54451784/63712824-78998300-c80c-11e9-91d4-47759d7010b1.png)

**Comment by mattsema** [comment]
fixed
