### ISSUE TITLE
Video Library sidebar filter

### ISSUE THREAD

**Issue by monicasyl10** [castl350/STEP#360]
Is there a way to have the sidebar filter to each topic simply by checking the topic? Currently it only filters after you check the topic and press search, which isn't very intuitive.

[http://dev.steplearning.org/resources/video_directory.php](url)

![image](https://user-images.githubusercontent.com/54451784/63904361-aafada00-c9de-11e9-8311-ca89ca0e9b99.png)

**Comment by mattsema** [comment]
expected functionality as keyword and checkbox can be linked in search
