### ISSUE TITLE
missing spaces & other errors

### ISSUE THREAD

**Issue by monicasyl10** [castl350/STEP#419]
there are several missing spaces in the text on this page. here is what it is supposed to be (other small errors also edited):

When children begin to work on addition, the "counting all" strategy is a great place to start. In this strategy, learners first count sets separately, then combine sets, then count the total starting at one. Often times, this strategy is first used with a "result unknown" problem, where we know the original number, and we know the amount that is added, but the result is unknown. However, in this video example, the teacher presents a more challenging addition problem called "change unknown", where the original amount is known (two squirrels) and the result is known (four squirrels) but the amount to add is unknown. As she presents the problem (How many squirrels do I have standing up here? How many more squirrels do I need to get to four?), several students present different answers. We hear one student respond with"one", and another student respond "two." The teacher then guides students to check both answers using the"counting all" strategy ("We had two. We added one. How many do we have altogether? One, two, three"). Throughout this process, she uses math language to emphasize the problem-solving steps taking place. When the group finally reaches the correct answer, the teacher encourages one student to check the answer using the "counting all" strategy. He counts the group of squirrels again, starting at one, to help the group determine there are now four squirrels total. Once again, the teacher uses math language to summarize the problem-solving process, "Good. We had two, and we added two more, and how many do we have altogether?"

[http://dev.steplearning.org/resources/player.php?v=1_ghysrdcm](url)

![image](https://user-images.githubusercontent.com/54451784/64201812-921a7a80-ce5d-11e9-8e99-85877486f0fa.png)

**Comment by mattsema** [comment]
fixed
