### ISSUE TITLE
numerals & typo

### ISSUE THREAD

**Issue by monicasyl10** [castl350/STEP#432]
numbers in the highlighted text in the screenshot below should be written out in words, and there is a punctuation typo. correct version of the highlighted text should be:

six bears on one "carpet" and then asking, "If I add one, two, on this carpet, how many do we have all together?" One student responds eight, and the teacher extends his mathematical thinking by elaborating on his answer. She models how to "count on" to solve an addition problem. "We know there's six on this carpet, so we're going to start with the next number: six, seven, eight!" The teacher extends mathematical thinking again when she asks students, "Do I always have to come back and start at the number one to count?"

[http://dev.steplearning.org/resources/player.php?v=1_5gesxac5](url)

![image](https://user-images.githubusercontent.com/54451784/64217906-51d2f080-ce8d-11e9-8b33-51d9dd8a0d8e.png)

**Comment by mattsema** [comment]
fixed
