### ISSUE TITLE
M0 S1 A1 - The Power of Early Math

### ISSUE THREAD

**Issue by mattsema** [castl350/STEP#5]
No video

**Comment by sarahlydic** [comment]
I believe this should be a lesson page that checks off after the learner views & should have a time estimate?

**Comment by castl350** [comment]
leaving open for video but other issue is moot.  it should not be a lesson page. It's a web page that will check off when learners view it, so they don't get the lesson complete page..etc..

**Comment by mattsema** [comment]
video added to lms
