### ISSUE TITLE
Three Big Ideas - video

### ISSUE THREAD

**Issue by psjiranek** [castl350/STEP#512]
Three Big Ideas - video

The text at the end of the video that Jessica says (and appears written on the screen): "Children's executive function and mathematics skills work hand-in-hand"

hand in hand should NOT be hyphenated as seen in the Check Your Knowledge: Three Big Ideas Quiz:

Question 1
Children's executive function and mathematics skills work hand in hand.

https://curryvirginia.instructure.com/courses/1418/pages/the-three-big-ideas?module_item_id=42824

**Comment by ryandkiley** [comment]
@sarahlydic

**Comment by sarahlydic** [comment]
n/a
