### ISSUE TITLE
Introduction and Objectives - Counting and Cardinality

### ISSUE THREAD

**Issue by psjiranek** [castl350/STEP#548]
Introduction and Objectives - Counting and Cardinality

After this session, you'll apply what you have learned about this skill as you:

Plan and practice implementing an activity in your classroom.
Observe your own implementation and reflect on your practice.

same question as raised before about whether this applies to the students taking this course?

https://curryvirginia.instructure.com/courses/1418/pages/introduction-and-objectives-counting-and-cardinality?module_item_id=43029

**Comment by sarahlydic** [comment]
n/a
