### ISSUE TITLE
Activity Times All

### ISSUE THREAD

**Issue by mattsema** [castl350/STEP#57]
need to be measured and entered

**Comment by sarahlydic** [comment]
need for M0 Your Turn - Objective & Descriptive

**Comment by castl350** [comment]
Sarah, just take your best guess and go with..The MO Your Turn will only have 3 videos..so i would say 5 minutes....the seeing how subtilizing develops should be hidden from learners? That activity did not get built for this time.

**Comment by sarahlydic** [comment]
All activity times added
