### ISSUE TITLE
Test Your Knowledge: Comparing and Ordering

### ISSUE THREAD

**Issue by psjiranek** [castl350/STEP#573]
Test Your Knowledge: Comparing and Ordering

This knowledge check is not graded, but you will receive feedback on correct and incorrect answers.

I just realized that all the TYKs say they are not grade (I think), but I am guessing that's not correct?

https://curryvirginia.instructure.com/courses/1418/quizzes/2942/take?preview=1

**Comment by sarahlydic** [comment]
n/a
