### ISSUE TITLE
M0 Your Turn - Missing video

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#61]
No source video was found error message for video 3

**Comment by castl350** [comment]
this video had some sort of encoding error causing to fail at random points
tried re-embedding multiple times, reuploading to kaltura, and converting using ffmpeg and reuploading to kaltura - problem still exists

may need to try to clip from source video again or find new video?

**Comment by sarahlydic** [comment]
Video is now appearing. Is this fixed? Let me know if you need with tracking down the source video?

**Comment by castl350** [comment]
Assigning to both of you to confirm that this is fixed.

**Comment by mattsema** [comment]
videos converted through screenflow and added to lms
