### ISSUE TITLE
Kaltura - landing images

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#70]
Just a note that some of the freeze frames that appear before playing the video capture awkward moments (like overlapping text and people in mid-phrase). Not sure if there's a way to change? (For next pilot probably.)

**Comment by castl350** [comment]
not something we can do anything about in the Kaltura system from what I remember Matt saying? Does it let you switch out still Matt? If no, just close. Not something we're going to fix now either.

**Comment by mattsema** [comment]
This requires that a video be re-embedded after going through kaltura to create and select a new thumbnail.
