### ISSUE TITLE
Numeracy S2 A3 - How Can You Support - Title reads 3D

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#71]
While these questions pertain to all of the pieces of this lesson (A3 A, B, C, and D), the title above the question says, "3D. Produce Sets of a Given Size" Can this be changed so it's clear the questions apply to all parts of A3?

**Comment by castl350** [comment]
I'm not sure what mean but i think this works good as is?

![screen shot 2016-10-14 at 11 37 09 am](https://cloud.githubusercontent.com/assets/3357288/19393413/9e517dac-9202-11e6-8366-cef7b88e97d5.png)
