### ISSUE TITLE
All About Numeracy

### ISSUE THREAD

**Issue by psjiranek** [castl350/STEP#716]
All About Numeracy

0:28-35 "as you can see, numeracy skills are important for lots of reasons and in this module, we'll explore four skills that young children are developing"

substitute "here" for "in this module" ?

0:46 - 52 "throughout this module, you'll get a chance to see teachers working to support children's numeracy skills..." 

just delete "throughout this module"

1:10 - delete "let's get started..."

https://curryvirginia.instructure.com/courses/3744/pages/all-about-numeracy?module_item_id=100446

**Comment by sarahlydic** [comment]
fixed
