### ISSUE TITLE
"Scores" displaying on iPad

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#73]
On the "You have completed this lesson" page, I get a message that displays my "score" (eg "Your score is 1 (out of 1).") 
Not sure if this can be removed?

**Comment by castl350** [comment]
I think this came up in toddler too..Matt, can you recall what we did? I think we left it because it's simply giving them a sense of how they did, not grading?

**Comment by mattsema** [comment]
The complicated nature of how these get put on the page meant that I could not remove this message without down-time.  We were leaving it until that time.
