### ISSUE TITLE
M0 S1 A7 - Completed lesson message

### ISSUE THREAD

**Issue by sarahlydic** [castl350/STEP#74]
For the "You have completed this lesson" page, on the tablet it displays the message, "Well done!"

**Comment by sarahlydic** [comment]
This is also true for M1 S2 A3 - A

**Comment by castl350** [comment]
that's nice? does it go on to the next lesson? Matt, can you check into this and see if there's anything we need to do?

**Comment by mattsema** [comment]
The "Well done!" is the equivalent to a graded lesson's message about score.  We discussed removing the score message when there is down time for the site.  That work will also include this message.
