### ISSUE TITLE
STEP 1 Checks in the check boxes

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#90]
Even though I have completed the activities, there are not check boxes ... I don't care so much - and they may not show up because of my level - but I know from experience that teachers can be VERY concerned about this ... not sure what can be done about it but if it's the sort of thing that is hard for us to control or is not going to be consistent ... then may be take out? Although I know it's there because it helps teachers know where they are.

**Comment by sarahlydic** [comment]
Some activities (those requiring a "grade" (answer at least one question)) won't get "checked off" for higher levels of admin access. They will get checked off in the Student role.
