### ISSUE TITLE
STEP 1 Session Follow-up Question 5 typo

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#92]
For the 3rd item the 'i' should be capitalized

For the 4th item - do teachers know that the terms iPad and tablet are interchangeable? Or should we be consistent in calling it one of the other? Or is that something that everyone knows?

For the 4th item in the list for c) the 'i' needs to be capitalized

**Comment by sarahlydic** [comment]
Made all changes. For 4th item -- changed term tablet to iPad for consistency
