### ISSUE TITLE
STEP 2 A1 What is it?

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#93]
The video is up higher and the continue button is way down low ... could be my desktop and using firefox, seems to be the case for the next video too (How It Develops)?

**Comment by sarahlydic** [comment]
@mattsema there's a lot of extra space between the video and the Continue button for 
Subitizing - What Is It? and Subitizing - How Does It Develop?

I don't want to take any essential pieces of code out accidentally. Can you fix?

**Comment by mattsema** [comment]
removed extra div causing space
