### ISSUE TITLE
STEP 2 TYK 

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#94]
Qu #2 typos - should be a comma after the word 'say'; 'yes' needs to be capitalized
Qu #3 typo - capitalize 'how' 'yes'
Qu #4 should there be a comma after 'the number word'
Qu #6 'teaching moves'? consider changing to teaching strategy - is that what we call them? Consider changing to, "... all of the following teaching strategies could be beneficial EXCEPT:
Qu #9 think should change to, "When a student can remember the number of objects that were on a card after the teacher quickly puts it away, the student is demonstrating ..." I am not 100% sure who the 'she' is how it is currently written - and I think that by putting 'the student' we're making it clear who is doing what and that student demonstrate executive function and not the teachers

**Comment by sarahlydic** [comment]
Made all changes. For Qu #6 changed "teaching moves" to "the following actions based on strategies could be beneficial..."
