### ISSUE TITLE
STEP 2 Plan (Part 1) typo, etc

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#95]
Not sure of ordering of 'foundational and targeted' strategies (if okay to switch order or if trying to be consistent and have it targeted and foundational strategies

Under number one - typos
your instead of you and plans instead of plan

Don't understand what you mean by 'coming up' do you mean #2? And it is kind of implied that I don't have to if I don't choose my own?
Maybe change to Planning Questions instead of Planning Exercise?

**Comment by sarahlydic** [comment]
Changed all typos in PLAN (part 1) in all courses. Changed "coming up" to "PLAN (part 2) planning exercise in all courses. Kept term "exercise" since this is interactive.
